# Generated by Django 5.2 on 2025-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_pricelist_pricelistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceListItem',
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='valid_until',
            field=models.DateTimeField(blank=True, default=None, help_text='Оставьте пустым для бессрочного действия', null=True, verbose_name='Дата окончания'),
        ),
    ]
