# Generated by Django 5.2 on 2025-04-19 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес отправки')),
                ('order_description', models.TextField(blank=True, default='', verbose_name='Описание заказа')),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес получателя')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость берется из услуги', max_digits=10, null=True, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
