# Generated by Django 5.2 on 2025-04-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('courier', 'Доставляет курьер'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Вручен'), ('partially_delivered', 'Частично вручен'), ('not_delivered', 'Не вручен')], default='courier', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
