# Generated by Django 5.2 on 2025-04-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Готов к доставке'),
        ),
    ]
