# Generated by Django 5.2 on 2025-04-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_order_claim_order_comment_order_courier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес отправки')),
                ('order_description', models.TextField(blank=True, default='', verbose_name='Описание заказа')),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес получателя')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость берется из услуги', max_digits=10, null=True, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('create', 'Создан'), ('courier', 'Доставляет курьер'), ('delivered', 'Вручен'), ('not_delivered', 'Не вручен'), ('cancelled', 'Отменен')], default='courier', max_length=20, verbose_name='Статус заказа')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('claim', models.TextField(blank=True, default=None, null=True, verbose_name='Претензия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('courier', models.ForeignKey(blank=True, limit_choices_to={'role__id': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders_courier', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to='delivery.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Выполненный заказ',
                'verbose_name_plural': 'Выполненные заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
